In [1]:
import pandas as pd 
import numpy as np
from IPython.display import display

In [ ]:
# 분류표 데이터 불러오기 

# 윈도우 
base_name_data = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2015_부문분류표.xlsx',  usecols=[0, 1, 2, 3, 4, 5, 6, 7],skiprows=[0, 1], sheet_name='상품분류표')

In [2]:
# 맥 
base_name_data = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/2015_부문분류표.xlsx',  usecols=[0, 1, 2, 3, 4, 5, 6, 7],skiprows=[0, 1], sheet_name='상품분류표')

In [ ]:
# 산업연관표 데이터 불러오기 

# 윈도우 

# 총 거래표 
base_data_2016 = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2016_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2017 = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2017_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2018 = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2018_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2019 = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2019_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])

total_base_data = [base_data_2016, base_data_2017, base_data_2018, base_data_2019]


# 국산거래표 
base_data_2016_domestic = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2016_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2017_domestic = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2017_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2018_domestic = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2018_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2019_domestic = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2019_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])


total_base_data_domestic = [base_data_2016_domestic, base_data_2017_domestic, base_data_2018_domestic, base_data_2019_domestic]

In [6]:
# 맥 

# 총 거래표 
base_data_2016 = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/2016_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2017 = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/2017_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2018 = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/2018_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2019 = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/2019_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])

total_base_data = [base_data_2016, base_data_2017, base_data_2018, base_data_2019]


# 국산거래표 
base_data_2016_domestic = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/2016_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2017_domestic = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/2017_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2018_domestic = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/2018_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2019_domestic = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/2019_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])

total_base_data_domestic = [base_data_2016_domestic, base_data_2017_domestic, base_data_2018_domestic, base_data_2019_domestic]

In [4]:
class Groupby_commodity():
        """
        0.1 초기 설정 
        """
        def __init__(self, total_data, total_data_domestic, name_data, year):
            
            self.total_data = total_data 
            self.total_data_domestic = total_data_domestic
            
            
            for i in range(4):
                self.total_data[i] = self.total_data[i].iloc[:, 1:].rename(columns={'Unnamed: 1':'상품분류'}).set_index('상품분류')
                self.total_data_domestic[i] = self.total_data_domestic[i].iloc[:, 1:].rename(columns={'Unnamed: 1':'상품분류'}).set_index('상품분류')
#                 data['대분류'] = list(pd.Series(data.index.values).apply(lambda x: dic_pre(x, dic)))

#                 data = data.replace(0, np.NaN)
            
            self.name_data = name_data 
            self.year = year 
        
        
            self.total_group_count = []
            self.group_name_list = []
            self.total_name_or_idx_list = []
            self.matching_dic = {}
         
            
        def standard_choise(self):   
            print('===================================')
            print('원하시는 분류 기준을 선택해주세요. ')
            print('1. 기본분류 \n 2. 소분류 \n 3. 중분류 \n 4. 대분류')
            choise = int(input('번호 선택 : '))
            print('분류 기준을 설정하였습니다.')
            print('===================================')
    
            if choise == 1: 
                self.name_data = self.name_data.iloc[:381, [0, 1]].dropna(how='any').reset_index(drop=True)
                self.group_name_len = len(self.name_data)
            elif choise == 2:
                self.name_data = self.name_data.iloc[:381, [2, 3]].dropna(how='any').reset_index(drop=True)
                self.name_data.columns = ['코드', '부문명']
                self.group_name_len = len(self.name_data)
            elif choise == 3:
                self.name_data = self.name_data.iloc[:381, [4, 5]].dropna(how='any').reset_index(drop=True)
                self.name_data.columns = ['코드', '부문명']
                self.group_name_len = len(self.name_data)
            else:
                self.name_data = self.name_data.iloc[:381, [6, 7]].dropna(how='any').reset_index(drop=True)
                self.name_data.columns = ['코드', '부문명']
                self.group_name_len = len(self.name_data)
                
                
                
        def name_select(self):
            display(self.name_data)
        
            group_count = int(input('해당 상품 분류들로 몇 개의 그룹을 생성하고 싶습니까?(최종 산업 개수): '))
            print()
            self.total_group_count.append(group_count)
            print('=== 그룹 개수 입력 완료 ===')
            print('======================================================')
            for i in range(1, group_count+1):
                name = input('{}번 그룹의 이름을 입력해주세요 : '.format(i))
                self.group_name_list.append(name)
            print('===', group_count,'개의 그룹 이름 입력 완료 ===')
            print(self.group_name_list)
            print('======================================================')
            
            
        def name_matching(self):
            print('최종 그룹 목록: {}'.format(self.group_name_list))
            print('======================================================')
            print('1. 각 그룹에 포함될 상품 분류의 인덱스 지정 \n 2. 각 그룹에 포함될 상품 분류의 이름 지정')
            
            index_or_name = int(input('어떤 방식으로 각각의 그룹에 포함될 상품 분류를 구성하시겠습니까?(번호 선택) : '))
            print('======================================================')
            
            # 중복값 찾기용 list
            overlap_list = []
            
            total_len = self.group_name_len
            total_list = []          
            for name in self.group_name_list:              
                name_or_idx_list = []
                if total_len == 0:   
                    break 
                if index_or_name == 1:
                    while True:                           
                        idx_range = input('{}에 포함시킬 상품 분류 인덱스 범위를 입력해주세요: ex) 1-{} '.format(name, self.group_name_len))                
                        try: 
                            idx_range = int(idx_range)
                            if idx_range in overlap_list or idx_range > self.group_name_len:
                                print()
                                print('범위를 초과했거나 이미 다른 그룹에 중복된 상품 분류가 포함되어 있습니다. 다시 입력해주세요. ')
                                print('사용된 상품분류 index 리스트: ')
                                print(overlap_list)
                                continue
                            total_len -= 1
                            name_or_idx_list.append(idx_range)
                            overlap_list.append(idx_range)
                        except:
                            idx_range_list = idx_range.split('-')
                            start_num = int(idx_range_list[0])
                            
                            final_num = int(idx_range_list[1])
                            
                            idx_range = [i for i in range(start_num, final_num+1)]
                            
                            overap = 0
                            
                            for idx in idx_range:
                                if idx in overlap_list or idx > self.group_name_len:
                                    print()
                                    print('범위를 초과했거나 이미 다른 그룹에 중복된 상품 분류가 포함되어 있습니다. 다시 입력해주세요. ')
                                    print('사용된 상품분류 index 리스트: ')
                                    print(overlap_list)
                                    overap = 1
                                    break
                            if overap != 0:
                                continue
                                        
                            name_or_idx_list.extend(idx_range)
                            overlap_list.extend(idx_range)
               
                            total_len -= final_num - start_num + 1 
                        
                        if total_len == 0:   
                            print()
                            total_list.append(name_or_idx_list)
                            print('0개의 그룹이 남았습니다. 분류 선택을 종료합니다.')
                            print('================================================')
                            break        
                        
                        next_y_n = input('{}개의 상품 분류 그룹이 남았습니다. 다음 산업으로 넘어가겠습니까?(yes or no) '.format(total_len))
                        print()
                        if next_y_n == 'yes':
                            if name == self.group_name_list[-1]:
                                print('마지막 그룹입니다. 나머지 상품 분류 인덱스를 추가해주세요')
                                continue
                            total_list.append(name_or_idx_list)
                            break
                        else:
                            continue    
                else:
                    while True:                  
                        c_name = input('{}에 포함시킬 상품 분류 이름을 입력해주세요: '.format(name))
                        if c_name in overlap_list or c_name not in list(self.name_data['부문명']):
                                print('이미 다른 그룹에 중복된 상품 분류가 포함되어 있거나 존재하지 않는 상품 분류입니다. 다시 입력해주세요. ')
                                print('사용된 상품분류 이름 리스트: ')
                                print(overlap_list)
                                continue
                        total_len -= 1               
                        overlap_list.append(c_name)
                        name_or_idx_list.append(c_name)                                 
                        if total_len == 0:   
                            print()
                            total_list.append(name_or_idx_list)
                            print('0개의 그룹이 남았습니다. 분류 선택을 종료합니다.')
                            print('================================================')
                            break                    
                        next_y_n = input('{}개의 상품 분류 그룹이 남았습니다. 다음 산업으로 넘어가겠습니까?(yes or no) '.format(total_len))        
                        print()
                        if next_y_n == 'yes':
                            if name == self.group_name_list[-1]:
                                print('마지막 그룹입니다. 나머지 상품 분류 인덱스를 추가해주세요')
                                continue
                        
                            total_list.append(name_or_idx_list)
                            break
                        else:
                    
                            continue
                                  
            self.total_name_or_idx_list.extend(total_list)
            dic = {}    
            for i, name in enumerate(self.group_name_list):
                dic[name] = self.total_name_or_idx_list[i]
                
            
            # 딕셔너리 뒤집기      
            for i, name in enumerate(a.group_name_list):
    
                for small_name in list(dic.values())[i]:

                    self.matching_dic[small_name] = name 
            
            # 만약 Index로 받아온 경우 인덱스를 상품명으로 바꿔서 딕셔너리를 형성해야함 
            if index_or_name == 1:
                total_idx = list(self.matching_dic.keys())
                
                for i in total_idx:
                    new_key = self.name_data.iloc[i-1][1]
                    self.matching_dic[new_key] = self.matching_dic.pop(i)

            print('분류 매칭을 완료했습니다.')
            print(self.matching_dic)
            print('=============================')
                
    
    def groupping(self):
        groupping_list = []
        metrix = self.total_group_count
        for data in total_base_data:
            data['그룹 분류'] = list(pd.Series(data.index.values[:self.group_name_len]).apply(lambda x: self.matching_dic[x])

            data = data.replace(0, np.NaN)

            metrix_a_1 = data.loc[:'중간투입계', :].groupby('그룹 분류').sum()
                                 
                                 
            metrix_b_1 = data.loc['중간투입계':, :]

            big_name_list_index = disting_standard[:metrix]
            big_name_list_index.extend(new_name)
            big_name_list_index.extend(list(metrix_b_1.index))

            metrix_total_1 = pd.concat([metrix_a_1, metrix_b_1], axis=0).transpose()


            metrix_total_1['그룹 분류'] = list(pd.Series(data.index.values[:self.group_name_len]).apply(lambda x: self.matching_dic[x])
            metrix_total_1 = metrix_total_1.replace(0, np.NaN)

            metrix_a_2 = metrix_total_1.loc[:'중간수요계', :].groupby('그룹 분류').sum()
            metrix_b_2 = metrix_total_1.loc['중간수요계':, :]

            metrix_total_2 = pd.concat([metrix_a_2, metrix_b_2], axis=0).transpose()

            metrix_total_2.drop('그룹 분류', axis=0, inplace=True)
            metrix_total_2.drop('그룹 분류', axis=1, inplace=True)

            metrix_total_2 = metrix_total_2.reindex(index=big_name_list_index, columns=big_name_list_columns)

In [7]:
a = Groupby_commodity(total_base_data, total_base_data_domestic, base_name_data, 2015)

,벼,맥류 및 잡곡,콩류,감자류,채소,과실,화훼작물,약용작물,잎담배,천연고무,...,수출,최종수요계,총수요계,총산출,수입,생산물세(수입),수입계,도소매마진,화물운임,총공급계\n
상품분류,,,,,,,,,,,,,,,,,,,,,
벼,110299,165,1156,2141,10602,689,328,21283,103,0,...,86.0,-114026.0,5693110.0,5693110.0,0.0,0.0,0.0,0.0,0.0,5693110.0
맥류 및 잡곡,0,2954,0,0,0,0,0,0,0,0,...,12035.0,-3368.0,3414892.0,255071.0,3144822.0,14999.0,3159821.0,0.0,0.0,3414892.0
콩류,0,0,7853,0,6827,0,0,0,0,0,...,1933.0,385915.0,1287657.0,606182.0,671351.0,10124.0,681475.0,0.0,0.0,1287657.0
감자류,0,0,0,31886,0,0,0,0,0,0,...,3333.0,417358.0,1098991.0,1071754.0,25801.0,1436.0,27237.0,0.0,0.0,1098991.0
채소,206,11,16,6,452,77,66,19,2,0,...,244879.0,6876213.0,12348365.0,11756215.0,453309.0,138841.0,592150.0,0.0,0.0,12348365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
영업잉여,4427925,178945,466703,673565,6261136,2770104,192008,1323541,45586,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
고정자본소모,507969,25239,19036,70350,1221839,508769,67227,159197,6039,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
생산세(보조금공제),-1624257,-18258,-37200,-65772,329219,58308,10406,58089,2232,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
부가가치계,3411487,195166,486502,805235,8794903,3684543,304088,1709604,65543,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
총투입계,5693110,255071,606182,1071754,11756215,4735884,584988,2074339,79686,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
a.standard_choise()

In [11]:
total = [1, 2, 3, 4 ,5]

In [12]:
for data in total:
    total

In [13]:
total

[1, 2, 3, 4, 5]

In [14]:
a.name_data

       코드      부문명    코드.1      부문명.1    코드.2   부문명.2  코드.3   부문명.3
0     111        벼    11.0  곡물 및 식량작물     1.0      작물     A   농림수산품
1     112  맥류 및 잡곡     NaN        NaN     NaN     NaN   NaN     NaN
2     113       콩류     NaN        NaN     NaN     NaN   NaN     NaN
3     114      감자류     NaN        NaN     NaN     NaN   NaN     NaN
4     121       채소    12.0    채소 및 과실     NaN     NaN   NaN     NaN
..    ...      ...     ...        ...     ...     ...   ...     ...
407  9801    영향력계수  9801.0      영향력계수  9801.0   영향력계수  9801   영향력계수
408  9802    감응도계수  9802.0      감응도계수  9802.0   감응도계수  9802   감응도계수
409  9819       열합  9819.0         열합  9819.0      열합  9819      열합
410  9812   구성비(%)  9812.0     구성비(%)  9812.0  구성비(%)  9812  구성비(%)
411  9811     유발계수  9811.0       유발계수  9811.0    유발계수  9811    유발계수

[412 rows x 8 columns]

In [ ]:
a.name_select()