In [1]:
import pandas as pd 
import numpy as np

In [49]:
# 분류표 데이터 불러오기 

# 윈도우 
base_name_data = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2015_부문분류표.xlsx',  usecols=[0, 1, 2, 3, 4, 5, 6, 7],skiprows=[0, 1], sheet_name='상품분류표')

In [37]:
# 맥 
base_name_data = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2015_부문분류표.xlsx',  usecols=[0, 1, 2, 3, 4, 5, 6, 7],skiprows=[0, 1], sheet_name='상품분류표')

In [3]:
# 산업연관표 데이터 불러오기 

# 윈도우 

# 총 거래표 
base_data_2016 = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2016_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2017 = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2017_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2018 = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2018_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2019 = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2019_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])

total_base_data = [base_data_2016, base_data_2017, base_data_2018, base_data_2019]


# 국산거래표 
base_data_2016_domestic = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2016_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2017_domestic = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2017_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2018_domestic = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2018_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2019_domestic = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2019_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])


total_base_data_domestic = [base_data_2016_domestic, base_data_2017_domestic, base_data_2018_domestic, base_data_2019_domestic]

In [ ]:
# 맥 

# 총 거래표 
base_data_2016 = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2016_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2017 = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2017_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2018 = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2018_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2019 = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2019_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])

total_base_data = [base_data_2016, base_data_2017, base_data_2018, base_data_2019]


# 국산거래표 
base_data_2016_domestic = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2016_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2017_domestic = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2017_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2018_domestic = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2018_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2019_domestic = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2019_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])

total_base_data_domestic = [base_data_2016_domestic, base_data_2017_domestic, base_data_2018_domestic, base_data_2019_domestic]

In [67]:
base_name_data.iloc[:381, [6, 7]].dropna(how='any').reset_index(drop=True)

   코드.3                부문명.3
0     A                농림수산품
1     B                  광산품
2   C01                 음식료품
3   C02            섬유 및 가죽제품
4   C03          목재 및 종이, 인쇄
5   C04            석탄 및 석유제품
6   C05                 화학제품
7   C06              비금속광물제품
8   C07              1차 금속제품
9   C08               금속가공제품
10  C09       컴퓨터, 전자 및 광학기기
11  C10                 전기장비
12  C11              기계 및 장비
13  C12                 운송장비
14  C13            기타 제조업 제품
15  C14    제조임가공 및 산업용 장비 수리
16    D          전력, 가스 및 증기
17    E   수도, 폐기물처리 및 재활용서비스
18    F                   건설
19    G        도소매 및 상품중개서비스
20    H                운송서비스
21    I          음식점 및 숙박서비스
22    J        정보통신 및 방송 서비스
23    K          금융 및 보험 서비스
24    L               부동산서비스
25    M      전문, 과학 및 기술 서비스
26    N              사업지원서비스
27    O      공공행정, 국방 및 사회보장
28    P                교육서비스
29    Q        보건 및 사회복지 서비스
30    R  예술, 스포츠 및 여가 관련 서비스
31    S               기타 서비스
32    T                   기타

In [44]:
print('===================================')
print('원하시는 분류 기준을 선택해주세요. ')
print('1. 기본분류 \n 2. 소분류 \n 3. 중분류 \n 4. 대분류')

print('===================================')

===================================
원하시는 분류 기준을 선택해주세요.
1. 기본분류
 2. 소분류
 3. 중분류
 4. 대분류
===================================

In [47]:
choise

NameError: name 'choise' is not defined

In [46]:
class Groupby_commodity():
    
    """
    0.1 초기 설정 
    """
    
    def __init__(self, total_data, total_data_domestic, name_data, year):
        self.total_data = total_data
        self.domestic_data = domestic_data 
        self.name_data = name_data 
        self.year = year 
        
        
        print('===================================')
        print('원하시는 분류 기준을 선택해주세요. ')
        print('1. 기본분류 \n 2. 소분류 \n 3. 중분류 \n 4. 대분류')
        choise = int(input('번호 선택 : '))
        print('===================================')
        
        if choise == 1: 
            self.name_data = name_data.iloc[:381, [0, 1]].dropna(how='any').reset_index(drop=True)
        elif choise == 2:
            self.name_data = name_data.iloc[:381, [2, 3]].dropna(how='any').reset_index(drop=True)
        elif choise == 3:
            self.name_data = name_data.iloc[:381, [4, 5]].dropna(how='any').reset_index(drop=True)
        else:
            self.name_data = name_data.iloc[:381, [6, 7]].dropna(how='any').reset_index(drop=True)
            
    
       """
    0.1 초기 분류 선택 
    """
        

    def choise_group(self):

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 12)