In [1]:
import pandas as pd 
import numpy as np
from IPython.display import display

In [2]:
# 분류표 데이터 불러오기 

# 윈도우 
base_name_data = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2015_부문분류표.xlsx',  usecols=[0, 1, 2, 3, 4, 5, 6, 7],skiprows=[0, 1], sheet_name='상품분류표')

In [ ]:
# 맥 
base_name_data = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2015_부문분류표.xlsx',  usecols=[0, 1, 2, 3, 4, 5, 6, 7],skiprows=[0, 1], sheet_name='상품분류표')

In [3]:
# 산업연관표 데이터 불러오기 

# 윈도우 

# 총 거래표 
base_data_2016 = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2016_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2017 = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2017_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2018 = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2018_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2019 = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2019_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])

total_base_data = [base_data_2016, base_data_2017, base_data_2018, base_data_2019]


# 국산거래표 
base_data_2016_domestic = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2016_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2017_domestic = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2017_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2018_domestic = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2018_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2019_domestic = pd.read_excel('C:/Users/Innovation/Desktop/김동요/jupyter/프로젝트/2019_투입산출표_생산자가격_기본부문.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])


total_base_data_domestic = [base_data_2016_domestic, base_data_2017_domestic, base_data_2018_domestic, base_data_2019_domestic]

In [ ]:
# 맥 

# 총 거래표 
base_data_2016 = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2016_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2017 = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2017_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2018 = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2018_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2019 = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2019_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_총거래표(생산자)", skiprows=[0, 1, 2, 3, 4])

total_base_data = [base_data_2016, base_data_2017, base_data_2018, base_data_2019]


# 국산거래표 
base_data_2016_domestic = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2016_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2017_domestic = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2017_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2018_domestic = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2018_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])
base_data_2019_domestic = pd.read_excel('/Users/dongyokim/main/jupyter /2022:Summer/2019_투입산출표_생산자가격_통합소분류.xlsx', sheet_name="A표_국산거래표(생산자)", skiprows=[0, 1, 2, 3, 4])

total_base_data_domestic = [base_data_2016_domestic, base_data_2017_domestic, base_data_2018_domestic, base_data_2019_domestic]

In [4]:
class Groupby_commodity():
        """
        0.1 초기 설정 
        """
        def __init__(self, total_data, total_data_domestic, name_data, year):
            
            self.total_data = total_data 
            self.total_data_domestic = total_data_domestic
            
            
            for i in range(4):
                self.total_data[i] = self.total_data[i].iloc[:, 1:].rename(columns={'Unnamed: 1':'상품분류'}).set_index('상품분류')
                self.total_data_domestic[i] = self.total_data_domestic[i].iloc[:, 1:].rename(columns={'Unnamed: 1':'상품분류'}).set_index('상품분류')
#                 data['대분류'] = list(pd.Series(data.index.values).apply(lambda x: dic_pre(x, dic)))

#                 data = data.replace(0, np.NaN)

            
        
            self.name_data = name_data 
            self.year = year 
            self.total_group_count = []
            self.group_name_list = []
            self.total_name_or_idx_list = []
            print('===================================')
            print('원하시는 분류 기준을 선택해주세요. ')
            print('1. 기본분류 \n 2. 소분류 \n 3. 중분류 \n 4. 대분류')
            choise = int(input('번호 선택 : '))
            print('===================================')

            if choise == 1: 
                self.name_data = name_data.iloc[:381, [0, 1]].dropna(how='any').reset_index(drop=True)
                self.group_name_len = len(self.name_data)
            elif choise == 2:
                self.name_data = name_data.iloc[:381, [2, 3]].dropna(how='any').reset_index(drop=True)
                self.name_data.columns = ['코드', '부문명']
                self.group_name_len = len(self.name_data)
            elif choise == 3:
                self.name_data = name_data.iloc[:381, [4, 5]].dropna(how='any').reset_index(drop=True)
                self.name_data.columns = ['코드', '부문명']
                self.group_name_len = len(self.name_data)
            else:
                self.name_data = name_data.iloc[:381, [6, 7]].dropna(how='any').reset_index(drop=True)
                self.name_data.columns = ['코드', '부문명']
                self.group_name_len = len(self.name_data)
                
                
                
        def name_select(self):
            display(self.name_data)
        
            group_count = int(input('해당 상품 분류들로 몇 개의 그룹을 생성하고 싶습니까?(최종 산업 개수): '))
            print()
            self.total_group_count.append(group_count)
            print('=== 그룹 개수 입력 완료 ===')
            print('======================================================')
            for i in range(1, group_count+1):
                name = input('{}번 그룹의 이름을 입력해주세요 : '.format(i))
                self.group_name_list.append(name)
            print('===', group_count,'개의 그룹 이름 입력 완료 ===')
            print(self.group_name_list)
            print('======================================================')
            
            
        def name_matching(self):
            print('최종 그룹 목록: {}'.format(self.group_name_list))
            print('======================================================')
            print('1. 각 그룹에 포함될 상품 분류의 인덱스 지정 \n 2. 각 그룹에 포함될 상품 분류의 이름 지정')
            
            index_or_name = int(input('어떤 방식으로 각각의 그룹에 포함될 상품 분류를 구성하시겠습니까?(번호 선택) : '))
            print('======================================================')
               
            total_len = self.group_name_len
            total_list = []
            for name in self.group_name_list:
                name_or_idx_list = []
                if index_or_name == 1:
                    while True:
                        idx_range = input('{}에 포함시킬 상품 분류 인덱스 범위를 입력해주세요: ex) 1-{} '.format(name, self.group_name_len))
        
                        try: 
                            idx_range = int(idx_range)
                            total_len -= 1
                            name_or_idx_list.append(idx_range)
                            
                        
                        except:
                            idx_range_list = idx_range.split('-')
                            start_num = int(idx_range_list[0])
                            
                            final_num = int(idx_range_list[2])
                            
                            idx_range = [i for i in range(start_num, final_num+1)]
                            name_or_idx_list.extend(idx_range)
                            
                            total_len -= final_num - start_num + 1 
                        next_y_n = input('{}개의 그룹이 남았습니다. 다음 산업으로 넘어가겠습니까?(yes or no) '.format(total_len))
                        print()
                        if next_y_n == 'yes':
                            total_list.append(name_or_idx_list)
                            break
                        else:
                            continue
                            
                            
                        
                        
                else:
                    while True:
                        name = input('{}에 포함시킬 상품 분류 이름을 입력해주세요: ')
                        
                        total_len -= 1
                        
                        print('입력하실 상품 분류 이름이 totla_len개 남았습니다.')
            self.total_name_or_idx_list.append(total_list)
    
        
        """
        0.1 초기 분류 선택 
        """
        

#     def choise_group(self):

In [5]:
a = Groupby_commodity(total_base_data, total_base_data_domestic, base_name_data, 2015)

===================================
원하시는 분류 기준을 선택해주세요.
1. 기본분류
 2. 소분류
 3. 중분류
 4. 대분류
번호 선택 : 4
===================================

In [6]:
a.name_select()

     코드                  부문명
0     A                농림수산품
1     B                  광산품
2   C01                 음식료품
3   C02            섬유 및 가죽제품
4   C03          목재 및 종이, 인쇄
5   C04            석탄 및 석유제품
6   C05                 화학제품
7   C06              비금속광물제품
8   C07              1차 금속제품
9   C08               금속가공제품
10  C09       컴퓨터, 전자 및 광학기기
11  C10                 전기장비
12  C11              기계 및 장비
13  C12                 운송장비
14  C13            기타 제조업 제품
15  C14    제조임가공 및 산업용 장비 수리
16    D          전력, 가스 및 증기
17    E   수도, 폐기물처리 및 재활용서비스
18    F                   건설
19    G        도소매 및 상품중개서비스
20    H                운송서비스
21    I          음식점 및 숙박서비스
22    J        정보통신 및 방송 서비스
23    K          금융 및 보험 서비스
24    L               부동산서비스
25    M      전문, 과학 및 기술 서비스
26    N              사업지원서비스
27    O      공공행정, 국방 및 사회보장
28    P                교육서비스
29    Q        보건 및 사회복지 서비스
30    R  예술, 스포츠 및 여가 관련 서비스
31    S               기타 서비스
32    T                   기타

해당 상품 분류들로 몇 개의 그룹을 생성하고 싶습니까?(최종 산업 개수): 5

=== 그룹 개수 입력 완료 ===
======================================================
1번 그룹의 이름을 입력해주세요 : 농림수산광업
2번 그룹의 이름을 입력해주세요 : 제조업
3번 그룹의 이름을 입력해주세요 : soc산업
4번 그룹의 이름을 입력해주세요 : 서비스업
5번 그룹의 이름을 입력해주세요 : 공간정보산업
=== 5 개의 그룹 이름 입력 완료 ===
['농림수산광업', '제조업', 'soc산업', '서비스업', '공간정보산업']
======================================================

In [7]:
a.name_matching()

최종 그룹 목록: ['농림수산광업', '제조업', 'soc산업', '서비스업', '공간정보산업']
======================================================
1. 각 그룹에 포함될 상품 분류의 인덱스 지정
 2. 각 그룹에 포함될 상품 분류의 이름 지정
어떤 방식으로 각각의 그룹에 포함될 상품 분류를 구성하시겠습니까?(번호 선택) : 1
======================================================

AttributeError: 'Groupby_commodity' object has no attribute 'total_len'